### ISSUE TITLE
Build a plugin playground component

### ISSUE THREAD

**Issue by johno** [unifiedjs/handbook#2]
This should be a react component that has panes for an input string (typically markdown), a code pane for manipulating the AST, and an output (which can stringify back to markdown, diff two ASTs, and render to HTML).

We can use this for example code blocks so folks can play around to better understand concepts.

The example usage might look something like:

````md
<RemarkPlayground plugins={['remark-slug']}>

```md type=input
# Hello, world!
```

```js type=plugin
module.exports = options = tree => {
  remove(tree, 'heading')
}
```

</RemarkPlayground>
````

**Comment by wooorm** [comment]
Closing as the repo will be archived; there is a playground on the remark site now, btw: https://remark.js.org.
